### ISSUE TITLE
::class.create error

### ISSUE THREAD

**Issue by dQqAn** [evant/kotlin-inject-samples#9]
I have 2 error with ::class.create in 2 file
 
first code and [file](https://github.com/evant/kotlin-inject-samples/blob/main/multiplatform/greeter/androidApp/src/main/java/com/fredporciuncula/inject/greeter/android/GreeterApplication.kt):
 
```
import android.app.Application

class GreeterApplication : Application(), ApplicationComponentProvider {
  override val component by lazy(LazyThreadSafetyMode.NONE) {
    ApplicationComponent::class.create(applicationContext)
  }
}
```

second code and [file](https://github.com/evant/kotlin-inject-samples/blob/main/multiplatform/greeter/androidApp/src/main/java/com/fredporciuncula/inject/greeter/android/MainActivity.kt): 
`val greeter = MainActivityComponent::class.create(applicationComponent).greeter`

In addition:
![image](https://github.com/evant/kotlin-inject-samples/assets/48219880/937401bb-e43e-487c-adf5-ed89bb66baf0)

i changed the type and there is a new error: 
![image](https://github.com/evant/kotlin-inject-samples/assets/48219880/dd949dc6-b97c-4a35-86ac-45b042aca043)

How can i fix this error?

**Comment by teewhydope** [comment]
same

**Comment by tfcporciuncula** [comment]
It's normal to see this error until you build the project so that function can be generated. Is the error still there after building the project? Can you check if for some reason you're not getting the generated code after a build?

<img width="1314" alt="Screenshot 2023-08-06 at 22 17 37" src="https://github.com/evant/kotlin-inject-samples/assets/750114/1747d845-10ff-4d32-b680-075ae3e96916">

I have no errors once the project is built:

<img width="593" alt="Screenshot 2023-08-06 at 22 18 18" src="https://github.com/evant/kotlin-inject-samples/assets/750114/7d4210c8-113f-44f5-b1b7-f5821bff1ad7">

**Comment by dQqAn** [comment]
thanks, i will try.
